{
 "title": "Main",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "A DNS Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx Requests per Minute",
   "type": "timeseries",
   "description": "Requests per Minute",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up\r\n", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "keepalived status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * (\r\n  sum(rate({job=\"haproxy\", service=\"haproxy\"} |~ \"^[23]\\\\d\\\\d \" [7d]))\r\n  /\r\n  sum(rate({job=\"haproxy\", service=\"haproxy\"} |~ \"^\\\\d{3} \" [7d]))\r\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "MySQL  SELECT Commands per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization on VMs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Consumption on VMs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Rate of Promtail Sent Entries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_entries_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Loki Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency of Agama",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(\r\n  avg_over_time(\r\n    {job=\"haproxy\"}\r\n    |~ \"\\\\d{3} \\\\d+\"\r\n    | regexp \"(?P<status_code>[0-9]{3}) (?P<request_time>[0-9.]+)\"\r\n    | unwrap request_time\r\n    [7d]\r\n  )\r\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "keepalived vrrp state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state\r\n", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Haproxy Server Status for each container",
   "type": "stat",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up",
     "legendFormat": "{{instance}}{{backend}}{{server}}{{status (0/1)}}"
    }
   ]
  }
 ]
}