{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Read-only status",
   "type": "stat",
   "gridPos": { "h": 21, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "A DNS Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication threads",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL  SELECT Commands per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}